[BOOK-16]-독후감 쓰기 수정 삭제 조회 API
team1-booklog/Backend pull request #11
Opened 2024-10-09 17:21 UTC by sungchaewon

일단 GPT, 구글과 함께 최대한 해봤습니다..(제가 노션을 잘못보고 BOOK-20-review 라는 브랜치를 잘못 만들었는데 지우는 게 안 된다고 떠서..그냥 뒀습니다..)
MySQL 연결은 노력해봤는데 계속 실패해서 못했습니다.
다들 바쁘신데 가장 쉬운 기능을 좋지 못한 완성도로 너무 늦게 올려서 죄송합니다..

2024-10-10 02:16 UTC, LeeHanEum reviewed
수고 많으셨습니다 👍 채원님 코드 기반으로 보완하겠습니다.

2024-10-10 15:27 UTC, LeeHanEum requested changes
수정할 부분이 조금 많이 나왔네요. 
하지만 앞으로 개발하시는데 많은 도움이 될 내용이니 잘 찾아보시면서 반영해주세요 👍

2024-10-10 15:27 UTC, LeeHanEum commented on src/main/java/goorm/unit/booklog/domain/review/domain/Review.java
> +@Setter
엔티티에 setter를 넣는건 위험한 코드인데요, setter를 넣으신 이유가 궁금합니다

2024-10-10 15:27 UTC, LeeHanEum commented on src/main/java/goorm/unit/booklog/domain/review/application/ReviewService.java
> +        review.setBook(bookService.getBook(request.book_id()));
엔티티에 setter를 넣는건 위험한 코드입니다. 
```java
public void updateTitle(String title){
   this.title = title;
}
```
review 엔티티에서 setter를 제거하고 엔티티 내부 코드를 위 코드와 같이 변경해주세요

2024-10-10 15:27 UTC, LeeHanEum commented on src/main/java/goorm/unit/booklog/domain/review/application/ReviewService.java
> +        reviewRepository.save(review);
`@Transactional` 어노테이션을 쓰면 save 메서드를 쓰지 않아도 자동 커밋 되면서 수정 사항이 반영됩니다.

2024-10-10 15:27 UTC, LeeHanEum commented on src/main/java/goorm/unit/booklog/domain/review/application/ReviewService.java
> +        review.setStatus("INACTIVE");
review 엔티티에서 status를 String이 아닌 enum으로 관리해주세요

2024-10-10 15:27 UTC, LeeHanEum commented on src/main/java/goorm/unit/booklog/domain/review/presentation/ReviewController.java
> +    @PutMapping("/{review_id}")
1. 새로운 객체로 변경하는게 아니기 때문에 Patch가 더 적절해보입니다. 
2. path에는 snake 타입이 아닌 camel 타입으로 변수명을 작성해주세요

2024-10-10 15:27 UTC, LeeHanEum commented on src/main/java/goorm/unit/booklog/domain/review/presentation/ReviewController.java
> +            @PathVariable @NotNull Long review_id, @Valid @RequestBody ReviewCreateRequest request) {
1. 매개변수간 개행 추가해주세요
2. `@Parameter` 어노테이션 추가해주세요. [여기 코드 참고](https://github.com/9oormthonUNIV-3th-KGU/family-note-server/blob/develop/src/main/java/goorm/kgu/familynote/domain/family/family/presentation/FamilyController.java)

2024-10-10 15:27 UTC, LeeHanEum commented on src/main/java/goorm/unit/booklog/domain/review/presentation/ReviewController.java
> +    @PatchMapping("/{review_id}")
마찬가지로 `@ApiResponse` 어노테이션 추가해주세요

2024-10-10 15:27 UTC, LeeHanEum commented on src/main/java/goorm/unit/booklog/domain/review/presentation/request/ReviewCreateRequest.java
> +import lombok.Getter;
record 자체에 getter 속성을 가지고 있기 때문에 불필요한 의존성 입니다.

2024-10-10 15:27 UTC, LeeHanEum commented on src/main/java/goorm/unit/booklog/domain/review/presentation/response/ReviewResponse.java
> +        LocalDateTime updatedAt
```java
@Schema(description = "생성일", example = "2024-09-12", requiredMode = REQUIRED)
@DateTimeFormat(pattern = "yyyy-MM-dd")
String createdAt
```
위 코드처럼 String으로 포맷팅해서 넘겨주세요

2024-10-10 15:27 UTC, LeeHanEum commented on src/main/java/goorm/unit/booklog/domain/review/presentation/response/ReviewResponse.java
>      public static ReviewResponse of(Review review) {
```java
public static ApplyResponse from (Apply apply) {
	DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
	return ApplyResponse.builder()
		.createdAt(apply.getCreatedAt().format(formatter))
		.build();
}
```
포맷팅 할 때 참고하면 좋은 코드 입니다.

2024-10-11 01:02 UTC, sunny2you commented on src/main/java/goorm/unit/booklog/domain/review/domain/Review.java
> +@Setter
앗 그렇군요. update 기능을 위해 넣었습니다. setter 대신 entity 안에 update 메소드를 따로 두는 방식으로 수정하도록 하겠습니다.

2024-10-11 01:14 UTC, sunny2you commented on src/main/java/goorm/unit/booklog/domain/review/application/ReviewService.java
> +        review.setBook(bookService.getBook(request.book_id()));
수정 기능도 작성 기능과 동일하게 네가지 속성(title, content, book_id, img)을 전부 넘겨받는 상황입니다. 그러면 updateReview 메소드 하나를 두고, 하나의 메소드 안에서 네가지 속성을 모두 변경할 수 있도록 해도 괜찮나요? 
아니면 예시로 알려주신 것처럼 updateTitle, updateContent.. 이런 식으로 속성 별로 update 메소드를 만들어야 맞는 걸까요? 이렇게 되면 4가지 속성 중 어떤 속성이 수정되었는지 확인하는 절차도 필요해보입니다.

2024-10-11 01:43 UTC, sunny2you commented on src/main/java/goorm/unit/booklog/domain/review/presentation/ReviewController.java
> +    @PutMapping("/{review_id}")
1번 사항에 대해 궁금한게 있습니다.  클라이언트가 업데이트 하는 필드만을 보낼 경우에는patch, 전체 필드를 보낼 경우에는 put으로 알고 있습니다. 현재 ui와 명세서에는 클라이언트가 전체 필드를 보내는 상황으로 되어있어 어떻게 해야할지 헷갈립니다..

2024-10-11 02:24 UTC, sunny2you commented on src/main/java/goorm/unit/booklog/domain/review/application/ReviewService.java
> +        review.setBook(bookService.getBook(request.book_id()));
우선은 updateReview 메소드를 하나만 두는 방식으로 하여 커밋 하였습니다!

2024-10-11 02:25 UTC, sunny2you commented on src/main/java/goorm/unit/booklog/domain/review/presentation/ReviewController.java
> +    @PutMapping("/{review_id}")
이 부분도 우선은 put으로 두고 커밋하였습니다!

2024-10-11 02:32 UTC, LeeHanEum commented on src/main/java/goorm/unit/booklog/domain/review/application/ReviewService.java
> +        review.setBook(bookService.getBook(request.book_id()));
재사용성을 고려해서 여러개의 메서드로 분리하는게 어떨까요? 분리하더라도 성능 상의 이슈는 없습니다.

2024-10-11 02:35 UTC, LeeHanEum commented on src/main/java/goorm/unit/booklog/domain/review/presentation/ReviewController.java
> +    @PutMapping("/{review_id}")
Put은 객체가 완전히 새로운 객체로 바뀔 때 사용하기 때문에 대부분 수정 API에서는 Patch를 씁니다. 지금도 Review 객체의 모든 필드가 100% 변경되는 것은 아니죠. Patch가 더 적절해 보입니다.

2024-10-11 02:39 UTC, sunny2you commented on src/main/java/goorm/unit/booklog/domain/review/presentation/ReviewController.java
> +    @PutMapping("/{review_id}")
두가지 사항 다시 반영하여 커밋하였습니다!

2024-10-11 02:58 UTC, LeeHanEum requested changes
좋은 코드 잘 봤습니다👍
정말 찐 마지막 수정 사항입니다.
폰으로 작성해서 설명이 좀 부족한데 궁금하신 점은 바로바로 물어보셔도 됩니다.

2024-10-11 02:58 UTC, LeeHanEum commented on src/main/java/goorm/unit/booklog/domain/book/application/BookService.java
> +				);
한 줄에 적어주시고 주석은 삭제해주세요

2024-10-11 02:58 UTC, LeeHanEum commented on src/main/java/goorm/unit/booklog/domain/book/application/BookService.java
> +				bookRepository.save(book);
.getId(); 해주시면 될거 같아요

2024-10-11 02:58 UTC, LeeHanEum commented on src/main/java/goorm/unit/booklog/domain/book/application/BookService.java
> +	public Book getBook(long id) {
Wrapper 클래스 Long 사용해주세요

2024-10-11 02:58 UTC, LeeHanEum commented on src/main/java/goorm/unit/booklog/domain/review/application/ReviewService.java
> +        );
한 줄에 적어주세요

2024-10-11 02:58 UTC, LeeHanEum commented on src/main/java/goorm/unit/booklog/domain/review/domain/ReviewStatus.java
> +    INACTIVE
Key, Description도 적어주세요. 다른 enum 참고!!

2024-10-11 02:58 UTC, LeeHanEum commented on src/main/java/goorm/unit/booklog/domain/review/presentation/request/ReviewCreateRequest.java
> +        Long book_id
BookResponse 객체를 전달하는건 어떨까요?

2024-10-11 04:16 UTC, sunny2you commented on src/main/java/goorm/unit/booklog/domain/review/presentation/request/ReviewCreateRequest.java
> +        Long book_id
Search하는 과정에서 book만 저장되고, file은 저장되고 있지 않음을 발견했습니다. 그래서 book 과 file 모두 각각의 테이블에 저장되도록 수정하였습니다. 

또한 특정 도서의 경우 description 길이가 1000을 넘어서 search를 시도할 시 오류가 나타났습니다. 
그래서 book 객체에서 description 속성의 길이를 1000에서 2000으로 늘려 해결했습니다.

2024-10-11 05:01 UTC, LeeHanEum approved these changes
수고하셨습니다

2024-10-11 05:01 UTC, merged