[BOOK-4]-feat: rds 세팅 및 무중단 배포 구현
team1-booklog/Backend pull request #3
Opened 2024-10-05 20:54 UTC by sunny2you

### 📍 issue number
[BOOK-4]-feat: rds 세팅 및 무중단 배포 구현
## *⛳️ Work Description*
- 기존에 설정되어 있던 docker mysql 컨테이너를 aws rds로 대체하였습니다.
- aws rds에 맞게 application.yml 을 수정하였습니다.
- deploy.yml을 추가해 무중단 배포를 구현하였습니다.
- github actions에 필요한 secrets 값을 저장하였습니다.  

## *📸 Screenshot*

*📢 To Reviewers*
- .env 파일은 노션에 두었습니다.

2024-10-06 02:30 UTC, LeeHanEum requested changes
워크플로 작성하느라 고생 많으셨습니다 👍
이전 pr의 내용이 중복되어 올라왔네요.
작업 전에 develop 브랜치 update 하셨었나요?

2024-10-06 02:30 UTC, LeeHanEum commented on src/main/resources/application.yml
> +    password: ${DB_PASSWORD}
application.yml의 datasource 관련설정은 원래대로 돌려주세요.
아마 인텔리제이 configuration에 Environment Variable을 세팅하지 않아서 DB 연결이 안되는 걸 거에요. 
환경변수 추가하고 다시 테스트 해보세요.

2024-10-06 02:46 UTC, sunny2you commented
리뷰 감사합니다.

datasource 관련 설정을 원래대로 돌려놓으라고 말씀하시는게, rds 말고 mysql 컨테이너를 사용하라는 말씀이신가요..??

원래 코드 기준으로 보면, 

${DB_HOST:localhost} 

이런 방식으로 써져있습니다. 환경변수의 기본값을 application.yml에서 바로 지정하는 코드라고 생각했는데 아닌가요..??

참고로 rds 로 변경하면서 함께 변경된 각 환경변수의 값은 노션에 올려두어 팀원들이 각자 .env파일을 세팅할 수 있도록 하였습니다. 

Sent from Naver Mail app.
-----Original Message-----
From: ***@***.***>
To: ***@***.***>
Cc: ***@***.***>, "State ***@***.***>
Sent: 2024. 10. 6 AM 11:30:46
Subject: Re: [team1-booklog/booklog-server] [BOOK-4]-feat: rds 세팅 및 무중단 배포 구현 (PR #3)

@LeeHanEum requested changes on this pull request.
워크플로 작성하느라 고생 많으셨습니다 👍
이전 pr의 내용이 중복되어 올라왔네요.
작업 전에 develop 브랜치 update 하셨었나요?
In src/main/resources/application.yml:
> @@ -2,9 +2,9 @@ spring: application: name: booklog-server datasource:- url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:booklog}?useSSL=false&allowPublicKeyRetrieval=true- username: ${DB_USERNAME:root}- password: ${DB_PASSWORD:root}+ url: ${DB_HOST}+ username: ${DB_USERNAME}+ password: ${DB_PASSWORD}
application.yml의 datasource 관련설정은 원래대로 돌려주세요.
아마 인텔리제이 configuration에 Environment Variable을 세팅하지 않아서 DB 연결이 안되는 걸 거에요.
환경변수 추가하고 다시 테스트 해보세요.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

2024-10-06 13:53 UTC, sunny2you commented on src/main/resources/application.yml
> +    password: ${DB_PASSWORD}
수정 완료 하였습니다! commit id : [44cea2d] 입니다.

2024-10-07 00:45 UTC, LeeHanEum commented
수고 많으셨습니다 👍

2024-10-07 00:47 UTC, LeeHanEum approved these changes
수고하셨습니다 👍

2024-10-07 00:47 UTC, merged