[BOOK-19]-아이디 중복 체크 API 분리
team1-booklog/Backend pull request #9
Opened 2024-10-09 11:53 UTC by sunny2you

[BOOK-19]-아이디 중복 체크 API 분리

## *⛳️ Work Description*
- 아이디 중복 체크 api를 /api/v1/users/duplication 으로 따로 분리하였습니다.
- request, response record 를 따로 생성하였습니다. 
- 테스트를 위해 알라딘 오픈 API 연동 관련 파일 (domain/file 폴더와 commom/config/FileUploadConfig.java 파일)을 exclude 해둔 상태입니다.
- application.yml에서 오픈 API 연동 관련 설정을 주석 처리 해둔 상태입니다. 

## *📸 Screenshot*

테스트 결과 

![Screenshot 2024-10-09 at 8 51 37 PM](https://github.com/user-attachments/assets/ba4a771f-cbfc-4d96-b87b-5a3c17ae94dd)

![Screenshot 2024-10-09 at 8 52 10 PM](https://github.com/user-attachments/assets/6ce52632-9256-4e3c-891b-7d670449e1db)

exclude 처리, 주석 처리 사항

![Screenshot 2024-10-09 at 8 52 32 PM](https://github.com/user-attachments/assets/ba9f0096-4a6e-4994-acbe-dfc2a636faa5)
![Screenshot 2024-10-09 at 8 52 57 PM](https://github.com/user-attachments/assets/6ae6b0fc-dc95-4800-a192-c22ec0522736)

*📢 To Reviewers*
-

2024-10-09 16:45 UTC, LeeHanEum requested changes
코멘트 확인 후 수정 부탁드립니다

2024-10-09 16:45 UTC, LeeHanEum commented on src/main/java/goorm/unit/booklog/domain/user/presentation/UserController.java
> +    }
불필요한 request response DTO 라고 생각됩니다. DTO 삭제 해주시고 Void API로 변경해주세요.

2024-10-09 16:45 UTC, LeeHanEum commented on build.gradle
> +	}
NCP 관련 환경변수가 들어가있지 않아서 에러가 나는걸 거에요.
노션에 해당 정보를 올려두었으니 위 설정은 지워주시고 yml 주석처리도 제거해주세요

2024-10-10 01:11 UTC, sunny2you commented
네 알겠습니다 


네이버 메일앱에서 보냈습니다.
-----Original Message-----
보낸사람: ***@***.***>
받는사람: ***@***.***>
참조: ***@***.***>, ***@***.***>
날짜: 2024. 10. 10 오전 1:46:04
제목: Re: [team1-booklog/booklog-server] [BOOK-19]-아이디 중복 체크 API 분리 (PR #9)

@LeeHanEum requested changes on this pull request.
코멘트 확인 후 수정 부탁드립니다
In src/main/java/goorm/unit/booklog/domain/user/presentation/UserController.java:
> + public ResponseEntity<DuplicationCheckResponse> checkUseridDuplication(+ @Valid @RequestBody DuplicationCheckRequest request+ ) {+ DuplicationCheckResponse response = userService.validateIdDuplication(request.id());+ return ResponseEntity.status(OK).body(response);+ }
불필요한 request response DTO 라고 생각됩니다. DTO 삭제 해주시고 Void API로 변경해주세요.
In build.gradle:
> +sourceSets {+ main {+ java {+ exclude 'goorm/unit/booklog/common/config/FileUploadConfig.java'+ exclude 'goorm/unit/booklog/domain/file/**'+ }+ }
NCP 관련 환경변수가 들어가있지 않아서 에러가 나는걸 거에요.
노션에 해당 정보를 올려두었으니 위 설정은 지워주시고 yml 주석처리도 제거해주세요
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were assigned.Message ID: ***@***.***>

2024-10-10 02:02 UTC, sunny2you commented on build.gradle
> +	}
두가지 코멘트 사항 반영하여 수정하였습니다. 확인 부탁드립니다.

2024-10-10 02:21 UTC, LeeHanEum approved these changes
수고하셨습니다 👍

2024-10-10 02:22 UTC, merged